### ISSUE TITLE
Archipelago Integration?

### ISSUE THREAD

**Issue by Tyeia** [CyrusKashef/BK_Randomizer#22]
Unsure whether this would be possible, or if the workload to do it would be insane. Archipelago is a multiworld multigame randomizer. Effectively it takes the triggers and items from a bunch of games and randomizes all of it. More accurate and detailed info can be found in [this doc](https://docs.google.com/document/d/e/2PACX-1vRLdz7L8PEH2LA6dUFXf7ibPjDnBYO_rLDVdt74fUh41YEbAn2ZTfFVCf9CET7q-OGFjoZEsMl1qnZc/pub). I was curious if integrating this randomizer with archipelago would be possible, since i've seen gameplay of this randomizer and it looks sick!

**Comment by CyrusKashef** [comment]
Hello! You're the fourth person to reach out to me about Archipelago ^_^ I love the enthusiasm and i think the integration would be a cool idea. However, I'm the only developer of the BK Rando, and I want to move onto Kirby 64. Maybe when the decomp comes out for BK, either I or someone else could make a better BK Rando and integrate it with AP. If someone wants to create the integration, I'm down to help, but I do not want to be the sole creator for this. I hope you understand :)

**Comment by Tyeia** [comment]
Perfectly understandable.
