### ISSUE TITLE
Various Bugs and Crashes in v1.01

### ISSUE THREAD

**Issue by SpencerLBrown** [CyrusKashef/BK_Randomizer#9]
Hi there. Sorry if this is not the right place to put this. I did not see any way to contact you regarding bugs

Seed # 18537589

Crashes:
- Clanker's Cavern move. In this seed, the move that is learned here is the running shoes. If you do not choose to skip the text (with L+R+B) and let the scene play out, the game crashes when it attempts to reference the second camera view that would normally be tied to the running shoes (assuming because only one camera view exists in this room).

Bugs:
- Infinitely recollectable jiggy. This exists in two locations, Click Clock Wood Spring by Eerie's nest, Click Clock Wood Fall inside the treehouse
- Infinitely recollectable Mumbo Token. This occurs in Gobi's Valley, the token is above Jinxy's nose
- A Mumbo Token in either Mumbo's Mountain, Click Clock Wood (replacing the TTC entrance), Mad Monster Mansion (replacing the CC entrance) or the token inside the sarcophagus in the GV lobby (replacing the jiggy) shares the same ID as the token inside the Witch's statue near the BGS lobby (replacing the jiggy that is normally obtained from the Witch Switch). Collecting it here results in it not existing later inside the statue.
- Possibly missing Jiggy in Treasure Trove Cove? Checked every single warp, item location, in the Lock-Ups, on the crates out in the ocean everywhere, and could only find 9/10. I seem to recall one of the Lock-Ups normally has an egg that was mistakenly placed below the level geometry and is inaccessible in normal game play. Perhaps it was placed there?

**Comment by CyrusKashef** [comment]
I'm so sorry for not seeing this earlier! I haven't been on my GitHub in those 3 months. I'll put some form of contact info in the ReadMe when I can get to it, but for now, I'll be checking here. Let me know if it's easier to talk through email, discord, or if we need to have something else.

Before I can fully test your seed, I'll need to know what settings you used. I'm sure you used Max Warps and Shuffle Jiggies/Honeycombs/Tokens, but did you have Misc Abnormalities turned on?

Crashes:
* I've actually seen someone have this crash before, but they didn't give me a seed value. I will test this out as soon as I can!

Bugs:
* Your first and second bullet points sound like the flags aren't registering for the item. I will look into those.
* Did not know about the Mumbo Token in the statue thing. I will test that out as well.
* Jiggies get swapped with Mumbo Tokens and Empty Honeycombs, so it cannot be the unreachable egg. However, I also push the unreachable egg up into the Lockup above it in case that ever becomes a note.
Here are your potential Jiggies in TTC for seed 18537589 with Misc Abnormalities turned on:
1. Blubber
2. Behind Nipper
3. Under the arch on a crate
4. X Marks The Spot Treasure Hunt
5. Jinjos
6. Inside the bottom of the lighthouse. This one will glitch IF you entered a warp to this Jiggy, but it should still appear on your totals screen, just not while you're in the world.
7. On top of the lighthouse
8. Under where Bottles normally teaches you flight
9. Nipper
10. Shock Jump Pad Alcove

Thank you for writing this, and I'm so sorry it took me so long to see it. I'm currently working on a v2.0.0 of the randomizer, and I'll keep these crashes/bugs in mind when working on it!

**Comment by SpencerLBrown** [comment]
Unfortunately, I don't remember now if I had Misc Abnormalities checked. Do you have any specific examples of what it would alter?

I will write that rom back to my Retroblaster cart and give it a try again sometime soon to see if I can figure out the Mumbo Token ID flag and if I can get all of the jiggies in TTC. It's possible for #6 that I entered via a warp, I can't remember anymore. All I remember is the jiggy counter displaying 9 once I left the level, and I don't remember anything such as collecting the 10th but having it not count.

**Comment by CyrusKashef** [comment]
Some misc abnormalities would be some of the eggs switching with jinjos and 1 ups. That's one that most people remember.

I really appreciate you looking into this. I've been meaning to look into it myself, but I have some personal things I'm trying to take care of, and I'm redoing most of the randomizer anyway, so I was going to see if the issues persisted there.

**Comment by Scapegoat02** [comment]
Yo! Not to hijack a thread, but I wanna get in contact for some additional info in your process of working with the ROM and figuring out values and such. I'm primarily on Discord nowadays, I don't mind sharin usernames if you're good with me contacting you.  This project is awesome friend.

**Comment by CyrusKashef** [comment]
Closing this thread because v2 may have solved these issues.
